### ISSUE TITLE
High priority

### ISSUE THREAD

**Issue by jessy0506** [blt950/vPilot-Pushover#11]
Hi,

Love this tool. How do I go about making the vPilot message a high priority message?

-jessy

**Comment by blt950** [comment]
Hi @jessy0506 , thanks for the question.

All messages where your callsign is tagged is already a high priority message. If there's a specific message you've in mind, send me a screenshot of the message. Open pushover app, click on the notification in question and screenshot that.

**Comment by blt950** [comment]
As I haven't heard back for three months, I'm closing this issue.
