### ISSUE TITLE
Can't get the Plugin to Load

### ISSUE THREAD

**Issue by TryFanGamer** [blt950/vPilot-Pushover#13]
After instaling i can't get the plugin to Load
![2024-01-15-0008z-53s_vPilot](https://github.com/blt950/vPilot-Pushover/assets/101999533/d6831714-c9f7-4ecf-9454-2b793db2f7a6)

![2024-01-15-0009z-26s_Plugins](https://github.com/blt950/vPilot-Pushover/assets/101999533/23ed72bc-b201-4cf8-80cd-c6dde2f1cbe6)

**Comment by TryFanGamer** [comment]
![2024-01-15-0013z-25s_vPilot_Debug_Messages](https://github.com/blt950/vPilot-Pushover/assets/101999533/fe62ed6b-46fa-46a8-8359-cdb069e7ce25)

**Comment by TryFanGamer** [comment]
It appears that the "RossCarlson.Vatsim.Vpilot.Plugins.dll" is making the Plugin fail...
I am still determining where this plugin is coming from, but after removing it, all is good.

**Comment by SlipstreamZA** [comment]
It appears you downloaded the "source" and not the actual release, download the file called **vPilot-Pushover-v1.0.1.zip** from the releases page https://github.com/blt950/vPilot-Pushover/releases, and you will see there is only 2 files in the zip that needs to be in vPilot plugin folder

vPilot-Pushover.dll
vPilot-Pushover.ini

Remember to configure the ini file with notepad

**Comment by TryFanGamer** [comment]
I did download the correct file i apers the RossCarlson.Vatsim.Vpilot.Plugins.dll a conflicting with the vPilot-Pushover.dll

**Comment by blt950** [comment]
pebkac, talked with TryFanGamer on Discord.
