### ISSUE TITLE
HOPE develop a new product. Such as xPilot-Pushover

### ISSUE THREAD

**Issue by JimmyKudo1015** [blt950/vPilot-Pushover#14]
HOPE develop a new product. Such as xPilot-Pushover
Work for Xplane11/12
Very Thanks

**Comment by blt950** [comment]
Hello, if I understand you correctly you're asking if there'll be a xPilot-Pushover.
No, not from me.

I don't own X-Plane and development for xpilot requires C++ which is an programming language I'm not familiar with. Hopefully someone can re-use parts of my open source code to create something similar 🙌

**Comment by imatomi** [comment]
Hi, I would like to fork this and shape it for X-Plane, please let me know how we can discuss this further.

**Comment by blt950** [comment]
@imatomi You're free to fork and copy the code according to the license in this repo. If you need anything else, you can add me on Discord. I've the same username as on Github.
