### ISSUE TITLE
Priority settings

### ISSUE THREAD

**Issue by rohaimkhedr** [blt950/vPilot-Pushover#16]
Could we get a setting in the .ini file where we can specify the priority for each message? That way I can keep my no disturb on, yet still receive vpilot notifications.

**Comment by blt950** [comment]
Hi @rohaimkhedr,
I can have a look into this. However all messages except ACARS are already high priority in Pushover and should bypass the DND. Is there any specific messages you have in mind?

**Comment by rxl211** [comment]
@rohaimkhedr I just found this app so I know I'm replying 5 months late but here is what I've done. It looks like by default high priority alerts don't break through DND. However, if you go into Pushover app settings just scroll down and enable "Critical Alerts for high-priority". You can further adjust the volume and also the sound (a bit further up see "Default high-priority sound". The sound "Persistent (long)" will surely do the trick to grab my attention.

Sorry for tagging you if you've already figured this out. But I guess this comment can still help anyone else who stumbles on this thread.

**Comment by blt950** [comment]
Closing this issue as it's stalled and probably resolved.
