### ISSUE TITLE
[Feature Request] Notify when disconnected

### ISSUE THREAD

**Issue by RudiZhang** [blt950/vPilot-Pushover#17]
Hi! Thanks for the great plugin! Would it be possible to add a function that pushes a notification if disconnected from the server? Thanks a lot!

**Comment by RudiZhang** [comment]
@rensdebee Thanks for your PR, but I will @blt950 is no more active :(:(

**Comment by blt950** [comment]
I'm here, I just haven't had time to check out this PR yet :)

**Comment by RudiZhang** [comment]
> I'm here, I just haven't had time to check out this PR yet :)

Oh. I’m sorry. 😅
