### ISSUE TITLE
not working at all 

### ISSUE THREAD

**Issue by cbrman11** [blt950/vPilot-Pushover#22]
i did all the troubleshooting steps and it still does not work  i even paid for it to try to make it work. vpilot doesnt seen say anthing about it try to load any help?

**Comment by blt950** [comment]
If you've followed the troubleshooting and it still doesn't work it's not much I can do. 

Try perhaps writing ".debug" immediately after vPilot starts to see if any debug print gives you any pointers. 

Paid or trial version of Pushover should not behave differently.

**Comment by blt950** [comment]
Closing here due to no response for months.
