### ISSUE TITLE
Add note to unblock .dll File

### ISSUE THREAD

**Issue by EisernUnion** [blt950/vPilot-Pushover#6]
Hi, on some windows systems downloaded files like exe or dll are blocked for security reasons

"
Open Microsoft Windows Explorer to locate and right-click the downloaded file, choose Properties from the context menu.
Click the Unblock button in the lower right-hand corner of the resulting dialog.
Click OK or Apply."

![0EMC0000000Hp1x (1)](https://github.com/blt950/vPilot-Pushover/assets/42810795/0b371748-21fc-41af-ae25-cebde2257bea)

**Comment by blt950** [comment]
Interesting, preferably I wouldn't like people to circumvent security feature as it just sounds shady even though the project is open source and clean.

I'll try to see if there's something I can do the file to not make it do this.

@EisernUnion Could you provide which OS and version you're on? That'd be relevant information to debug this.
