### ISSUE TITLE
Pushover doesn't work with vPilot(V3.7.0)

### ISSUE THREAD

**Issue by grafm82** [blt950/vPilot-Pushover#9]
Hello, I have configured everything as described in the instructions. However, I am not receiving any messages from vPilot. After opening vPilot I should get the 1 push, but it doesn't come. Maybe you can check that again.

Thank you

**Comment by blt950** [comment]
Hi @grafm82 , 

I've verified that the v1.0.1 version of the plugin works with vPilot v3.7.0 and have not yet received any similar issues from others.

It's correct as you say that you should get 1 push after you start vPilot saying "connected". I can think of two reasons of why it's not running:
1. The plugin is not placed in the correct folder and not loading
2. The pushover API key is incorrect or missing, so it never goes through

To debug this, start vPilot and quickly (before it manages to complete loading) write `.debug` in the console. Then it should inform you of which plugins are loaded and also eventual errors from the plugin if something went wrong there.

**Comment by grafm82** [comment]
The files are located in the folder C:\Users\xxx\AppData\Local\vPilot\Plugins.
I checked the API and user key several times.
I saw a YouTube video somewhere that a push was sent after starting vPilot. But I can't get this either. I'll take a look at the debug in vPilot.
I get this error in debug:
Error loading plugin from file "C:\Users\xxx\AppData\Local\vPilot\Plugins\vPilot-Pushover.dll": The file or assembly "file:///C:\Users\xxx\AppData\Local\vPilot \Plugins\vPilot-Pushover.dll" or a dependency on it was not found. The operation is not supported. (Exception from HRESULT: 0x80131515)

**Comment by grafm82** [comment]
[13:27:28.101] vPilot version 3.7.0
[13:27:29.316] Attempting simulator connection...
[13:27:29.316] Error loading plugin from file "C:\Users\Markus\AppData\Local\vPilot\Plugins\vPilot-Pushover.dll": Die Datei oder Assembly "file:///C:\Users\Markus\AppData\Local\vPilot\Plugins\vPilot-Pushover.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Der Vorgang wird nicht unterstützt. (Ausnahme von HRESULT: 0x80131515)
[13:27:29.751] Simulator connection failed.
[13:27:34.309] Attempting simulator connection...
[13:27:34.751] Simulator connection failed.
[13:27:39.306] Attempting simulator connection...
[13:27:39.746] Simulator connection failed.
[13:27:44.309] Attempting simulator connection...
[13:27:44.741] Simulator connection failed.

**Comment by grafm82** [comment]
I accidentally came across closed comments!

**Comment by blt950** [comment]
That's weird. vPilot seems to know the plugin exists, otherwise it wouldn't try to load it, though something fails when loading it. Meaning it's not the config.

Could you try opening the properties of the `vPilot-Pushover.dll` file? See if you have a unblock button like this? I'll never endorse to circumvent security settings, but I know another user reported this as an thing that stopped it from working earlier.
![image](https://github.com/blt950/vPilot-Pushover/assets/2505044/9e33a54c-4db3-4ed6-8a53-46c765a6b416)


Also, out of curiousity, which Youtube video did you watch?

**Comment by grafm82** [comment]
Now the push works. It was due to the properties of the file.
I searched on YouTube and found this video:
https://www.youtube.com/watch?v=DmdcBPesNjQ&t=272s

Thank you for the quick help

**Comment by blt950** [comment]
> Now the push works. It was due to the properties of the file.
> 
> I searched on YouTube and found this video:
> 
> https://www.youtube.com/watch?v=DmdcBPesNjQ&t=272s
> 
> 
> 
> Thank you for the quick help

@grafm82 Could you kindly share what kind of properties you changed to make it work? So I know what to answer if others experience the same issue :)

**Comment by grafm82** [comment]
I allowed the file to be secure as described above
